# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ALTERNATE_CORE_PATH = ../../digispark
ARDUINO_CORE_PATH = ../../digispark/cores/tiny
ARDUINO_DIR = ../../digispark
BOARD_TAG = attiny
MCU = attiny85
F_CPU = 16000000L
ISP_PROG = micronucleus
ARDUINO_LIBS = DigisparkJoystick

include ../../Arduino.mk
